### PR TITLE
Let to use different table name

### PR DESCRIPTION
**Pull request by shandak**
There is a proposal that let the user use a different migration table name

### CODE REVIEW

**Comment by iamsauravsharma** [comment]
Can you write commit message using https://www.conventionalcommits.org/en/v1.0.0/ format and sign commit https://github.com/iamsauravsharma/sqlx_migrator/pull/17/checks?check_run_id=13307023981 as explained. Test also failed can you improve commit so test can pass

**Comment by shandak** [comment]
For some reason, I can't configure properly "Signed-off-by" I get "Screen or window too small" even size of the console is max. I probably would not pass it.

**Comment by shandak** [comment]
Feel free to rewrite this PR if you need "Signed-off-by", it's not necessary that show me as a contributor or something.

**Comment by iamsauravsharma** [comment]
@shandak After careful consideration I regret to inform you I don't think different table name can be supported by library itself since supporting it will also include vulnerability related to SQL injection in library. So I have made decision to not include this feature to protect my library user from possible SQL injection. I will improve documentation of library to include documentation of how to implement custom migrator which support different table name.

**Comment by iamsauravsharma** [comment]
Feel free to open new PR if you can mitigate SQL injection possibilities while supporting different table name

**Comment by shandak** [comment]
> Feel free to open new PR if you can mitigate SQL injection possibilities while supporting different table name

To be honest, I do not see what kind of SQL injection can be applied there. The table name is a part of the lib configuration, I think this part is able only for backenders when they add dependencies, it's up to them how to configure, I think.
If then don't need to change the table name that they won't.

**Comment by iamsauravsharma** [comment]
@shandak I am aware that only the backend user can write table name but If the backend developer developed some functionality based on this feature where their end user can provide input for table name there is a chance of SQL injection if the user input is not validated or sanitized properly before being used to construct the table name. I have no control to block this use case and validate user input is sanitized propel. So, I am blocking this use case directly from the library.

One solution is to validate table name directly on sqlx migrator code so backend developer cannot pass table name which can introduce SQL injection chances.

Feel free to open new PR if you add functionality to validate/sanitize table name input directly on sqlx migrator. So, backend developer cannot introduce SQL injection

**Comment by iamsauravsharma** [comment]
@shandak You can always introduce SQL injection if user input is not sanitized and validated properly. Feel free to open new PR where table name is sanitized properly. You can use `^[a-zA-Z_][a-zA-Z0-9_]*$` regex for sanitizing table name

**Comment by iamsauravsharma** [comment]
@shandak You can always introduce SQL injection if user input is not sanitized and validated properly. Current PR doesn't sanitize table name since library have no control to validate backend developer have done any mistake or not while passing table name so there is always chance for sql injection if table name parameter values depends on user input

**Comment by iamsauravsharma** [comment]
As an example lets say backend developer added feature where their end users can provide table name(possible for some unique use case we have no control to block this use case) then end user provides table name as `_test_table_name; drop table users; --` then this end user input is sql injection attack and drop full users tables. I do not know any use case where two different unrelated projects needs same database when one single database server easily support multiple database.

**Comment by iamsauravsharma** [comment]
@shandak version v0.9.2 added support for custom table name for migrator which have some limitation i.e it only support adding prefix to original table name, only support ascii alpha numeric character or underscope as prefix other keys are unsupported

**Comment by shandak** [comment]
Looks awesome @iamsauravsharma ! Thank you for it!

**Pull request closed without merging**
